version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres